services:
  telemt:
    image: ghcr.io/telemt/telemt:3.4.13
    container_name: telemt
    restart: unless-stopped
    network_mode: host
    environment:
      TZ: Europe/Moscow
    healthcheck:
      test: ["CMD", "/app/telemt", "healthcheck", "/app/config.toml", "--mode", "liveness"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 20s
    logging:
      driver: journald
      options:
        tag: "{{.Name}}"
    volumes:
      - /opt/mtproto/telemt/config.toml:/app/config.toml:ro
      - /opt/mtproto/telemt/data:/var/lib/telemt:rw
